pipeline:
  identifier: Build_sandbox_1707156661808
  name: Build sandbox
  orgIdentifier: default
  projectIdentifier: sandbox
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: githubtoken
        repoName: sandbox
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: check dependencies
                  identifier: check_dependencies
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.8-jdk-11
                    shell: Sh
                    command: |-
                      mvn dependency-check-maven:check -U -DskipTests
                       reports:
                         type: JUnit
                         spec:
                           paths:
                             - /harness/target/*.xml
              - step:
                  type: Run
                  name: build
                  identifier: compile
                  spec:
                    shell: Sh
                    command: mvn compile
              - step:
                  type: Run
                  name: execute
                  identifier: execute
                  spec:
                    shell: Sh
                    command: gradle buildRun
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.8-jdk-11
                    shell: Sh
                    command: mvn clean package dependency:copy-dependencies
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
