pipeline:
  identifier: Build_sandbox_1707156661808
  name: Build sandbox
  orgIdentifier: default
  projectIdentifier: sandbox
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: githubtoken
        repoName: sandbox
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: compile
                  spec:
                    connectorRef: Docker_Registry
                    image: amd64/eclipse-temurin:latest
                    shell: Sh
                    command: mvn -DskipTests package
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
